### ISSUE TITLE
web videos on Safari

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/tours#1] opened 2024-04-09 07:03 UTC
Video links like [https://commons.wikimedia.org/w/index.php?title=Special:Redirect/file/Intense_bone_fluorescence_reveals_hidden_patterns_in_pumpkin_toadlets_-_video_1_-_41598_2019_41959_MOESM2_ESM.webm](https://commons.wikimedia.org/w/index.php?title=Special:Redirect/file/Intense_bone_fluorescence_reveals_hidden_patterns_in_pumpkin_toadlets_-_video_1_-_41598_2019_41959_MOESM2_ESM.webm) don't seem to play for me in the embedded `<video src="xxx">` tag in Safari/OS X. However, on wikipedia commons the video plays within a video tag just fine, because they use a url to a transcoded version in the `src` tag, at [https://upload.wikimedia.org/wikipedia/commons/transcoded/f/f5/Intense_bone_fluorescence_reveals_hidden_patterns_in_pumpkin_toadlets_-_video_1_-_41598_2019_41959_MOESM2_ESM.webm/Intense_bone_fluorescence_reveals_hidden_patterns_in_pumpkin_toadlets_-_video_1_-_41598_2019_41959_MOESM2_ESM.webm.1080p.vp9.webm](https://upload.wikimedia.org/wikipedia/commons/transcoded/f/f5/Intense_bone_fluorescence_reveals_hidden_patterns_in_pumpkin_toadlets_-_video_1_-_41598_2019_41959_MOESM2_ESM.webm/Intense_bone_fluorescence_reveals_hidden_patterns_in_pumpkin_toadlets_-_video_1_-_41598_2019_41959_MOESM2_ESM.webm.1080p.vp9.webm).

The various transcoded versions are listed under the video, at [https://commons.wikimedia.org/wiki/File:Intense_bone_fluorescence_reveals_hidden_patterns_in_pumpkin_toadlets_-_video_1_-_41598_2019_41959_MOESM2_ESM.webm#transcodestatus](https://commons.wikimedia.org/wiki/File:Intense_bone_fluorescence_reveals_hidden_patterns_in_pumpkin_toadlets_-_video_1_-_41598_2019_41959_MOESM2_ESM.webm#transcodestatus), and there are a number of transcoded versions available: I wonder if @lentinj has any idea which would be the best to pick? The Wikimedia embedded video play lists a whole load of them in the `<source>` tags, which I assume serve as fallbacks for e.g. for use on mobile.

Either way, it would be good to be able to use the safari-compatible version in tours somehow. Can you think of an easy way @lentinj ?

**Comment by jrosindell** [comment] 2024-04-09 10:21
Just to add to this.... the tour videos from Wikimedia are working on Safari now both locally and on the beta site.

**Comment by hyanwong** [comment] 2024-04-09 11:48
It may be a race condition associated with https://github.com/OneZoom/OZtree/issues/783

**Comment by lentinj** [comment] 2024-04-15 09:02
Duplicate of https://github.com/OneZoom/OZtree/issues/773

**Closed by lentinj** 2024-04-15 09:02 UTC
